language: java
dist: trusty
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: axel3rd-github
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.pullrequest.branch=$TRAVIS_BRANCH
deploy:
  provider: bintray
  file: bintray-descriptor.json
  user: axel3rd
  key: $BINTRAY_API_KEY
  skip_cleanup: true